### ISSUE TITLE
how to translate ng-formio-builder dependency

### ISSUE THREAD

**Issue by hank123** [formio/formio-app-formbuilder#4]
I am able to use angular-translate to translate  formio-app-formbuilder, I am able to translate the static messages in this same project(module),  but I am not sure how to translate ngFormBuilder which is a dependency module of this project, since all the components like button, textfield etc are comming from this module, so that I need these component to be translated into different language,  do I need to configure ngFormBuilder same way as I did for formio-app-formbuilder ? I added 'pascalprecht.translate' to the index.module.js and also added '$translateProvider',
 '$locationProvider' etc to index.config.js  for the formio-app-formbuilder project, and also added an static translation file which contains the key/values for translation, do I need to do all this again for ngFormBuilder or just replace the "keys"(whatever need to be translated) with the translation expression ?  because ngFormBuilder is an dependency, I don't know if the configuration I made to the main module will apply to it also.

Regards !

Hank123

**Comment by jgldev** [comment]
Same problem happened to me, anyone knows how we should use the $translateProvider to translate the fields validations?
